# Change these first
owner: alexinabox # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Anxiety
    check: "tcp-ping"
    url: $ANXIETY_IP
    port: 22
  - name: Bliss
    check: "tcp-ping"
    url: $BLISS_IP
    port: 22
  - name: Curiosity
    check: "tcp-ping"
    url:  $CURIOSITY_IP
    port: 22
  - name: Base
    check: "tcp-ping"
    url:  $BASE_IP
    port: 22
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zeitvertreib.vip
  # baseUrl: /your-repo-name
  logoUrl: https://zeitvertreib.vip/assets/logos/logo_full_color_1to1.png
  name: Zeitvertreib Status!!
  introTitle: "OMG! Das ist die echte **Zeitvertreib** Status Seite!! Wie cool..!"
  introMessage: "Das sind so alle Server in meiner **Infrastruktur**! Auf dem **Discord Server** ist es aber vieeeel cooler: [**Beitreten!**](https://dsc.gg/zeit)"
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://dsc.gg/zeit
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
